### ISSUE TITLE
Opening cmdwin from mundo window spews errors coming from MundoRefreshDelayed

### ISSUE THREAD

**Issue by idbrii** [simnalamburt/vim-mundo#112]
If you open cmdwin (default `q:` or `:<C-f>`) from inside the mundo window, you get a screen full of errors.

# Minimal vimrc

```vim
" Invoke with:
" vim -Nu ~/.vim/reprovimrc.vim -U NONE

" all plugins should work with sensible as a baseline.
let s:plugins = ['sensible']
let s:plugins += ['mundo']

set runtimepath-=~/.vim
set runtimepath-=~/.vim/after
set runtimepath-=~/vimfiles
set runtimepath-=~/vimfiles/after
for plugin in s:plugins
    exec "set runtimepath^=~/.vim/bundle/". plugin
    exec "set runtimepath+=~/.vim/bundle/". plugin ."/after"
endfor
set viminfofile=NONE

" Point to your python
let $PATH = $PATH .. ';' .. expand('$USERPROFILE/scoop/apps/python39/3.9.1/')

nnoremap <F2> :<C-u>MundoToggle<CR>
nnoremap <F3> q:
```

# Repro

1. `gvim -Nu ~/.vim/reprovimrc.vim -U NONE c:\scratch\bug.txt`
1. F2
1. F3

You get these errors:

```
Error detected while processing function <SNR>29_MundoRefreshDelayed[11]..<SNR>29_MundoPythonRestoreView[17]..<SNR>29_MundoPython[1]..function <SNR>29_MundoRefreshDelayed[11]..<SNR>29_MundoPythonRestoreView[17]..<SNR>29_MundoPython:
line    1:
Traceback (most recent call last):
Error detected while processing function <SNR>29_MundoRefreshDelayed[11]..<SNR>29_MundoPythonRestoreView[17]..<SNR>29_MundoPython[1]..function <SNR>29_MundoRefreshDelayed[11]..<SNR>29_MundoPythonRestoreView[17]..<SNR>29_MundoPython:
line    1:
  File "<string>", line 1, in <module>
Error detected while processing function <SNR>29_MundoRefreshDelayed[11]..<SNR>29_MundoPythonRestoreView[17]..<SNR>29_MundoPython[1]..function <SNR>29_MundoRefreshDelayed[11]..<SNR>29_MundoPythonRestoreView[17]..<SNR>29_MundoPython:
line    1:
  File "C:\\Users\\idbrii\\.vim\\bundle\\mundo\\autoload/mundo.py", line 94, in MundoRenderGraph
Error detected while processing function <SNR>29_MundoRefreshDelayed[11]..<SNR>29_MundoPythonRestoreView[17]..<SNR>29_MundoPython[1]..function <SNR>29_MundoRefreshDelayed[11]..<SNR>29_MundoPythonRestoreView[17]..<SNR>29_MundoPython:
line    1:
    util._goto_window_for_buffer('__Mundo__')
Error detected while processing function <SNR>29_MundoRefreshDelayed[11]..<SNR>29_MundoPythonRestoreView[17]..<SNR>29_MundoPython[1]..function <SNR>29_MundoRefreshDelayed[11]..<SNR>29_MundoPythonRestoreView[17]..<SNR>29_MundoPython:
line    1:
  File "C:\Users\idbrii\.vim\bundle\mundo\autoload\mundo\util.py", line 33, in _goto_window_for_buffer
Error detected while processing function <SNR>29_MundoRefreshDelayed[11]..<SNR>29_MundoPythonRestoreView[17]..<SNR>29_MundoPython[1]..function <SNR>29_MundoRefreshDelayed[11]..<SNR>29_MundoPythonRestoreView[17]..<SNR>29_MundoPython:
line    1:
    vim().command('%dwincmd w' % int(winnr))
Error detected while processing function <SNR>29_MundoRefreshDelayed[11]..<SNR>29_MundoPythonRestoreView[17]..<SNR>29_MundoPython[1]..function <SNR>29_MundoRefreshDelayed[11]..<SNR>29_MundoPythonRestoreView[17]..<SNR>29_MundoPython:
line    1:
vim.error: Vim(wincmd):E11: Invalid in command-line window; <CR> executes, CTRL-C quits
```

# Version

mundo 2a12e25c4236a46d09e4d038560f0412bbdb117f

**Comment by simnalamburt** [comment]
Could reproduce this issue with neovim v0.7.2, Python v3.10.5, pynvim v0.4.3, vim-mundo 3c7e008.
