### ISSUE TITLE
Searh error on Windows

### ISSUE THREAD

**Issue by xtal8** [simnalamburt/vim-mundo#61]
When searching for pattern in undo history and there are no results, the following error is thrown

```vim
Error detected while processing function <SNR>76_MundoPython:
line    2:
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "C:\\Users\\Marko\\vimfiles\\plugged\\vim-mundo\\autoload/mundo.py", line 272, in MundoSearch
    MundoNextMatch()
  File "C:\\Users\\Marko\\vimfiles\\plugged\\vim-mundo\\autoload/mundo.py", line 280, in MundoNextMatch
    MundoMatch(1)
  File "C:\\Users\\Marko\\vimfiles\\plugged\\vim-mundo\\autoload/mundo.py", line 306, in MundoMatch
    undochanges = nodesData.preview_diff(nmap[version].parent, nmap[version])
KeyError: 6
```

**Comment by dsummersl** [comment]
Oh! Thank  for you this, I think it happened to me recently. I'll try and take a look at it toady.

**Comment by dsummersl** [comment]
I've had no luck reproducing this - anyone else? If so how (and what verrsion of vim)?

**Comment by simnalamburt** [comment]
Lack of windows development environment.. 😭 sorry

**Comment by dylnmc** [comment]
Windows `:MundoToggle` has been extraordinarily slow. Is this related or another issue? I get no errors; it's just REALLLLLY slow

(Sometimes it takes over a minute just to open `:MundoToggle` .. by which time I have inevitably forgotten *why* I was opening it. Also, I can't `<c-c>` because it ruins my history and I have to `:q!`.)

**Comment by dylnmc** [comment]
I have to develop on windows at work. I just ran into this issue. Also the first time I open mundo with an undo history greater than 1000 undos, it is *still* really slow. I also just ran into this `KeyError: 9` issue. Will try to look into this at home, but I only run linux at home 😭

**Comment by dsummersl** [comment]
@dylnmc please try the latest version (merged in a PR that should improve rendering today).
